version: "3.8"
services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    restart: always
    ports:
      - 13306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: process.env.MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
      MYSQL_USER: process.env.MYSQL_USER
      MYSQL_PASSWORD: process.env.MYSQL_PASSWORD
volumes:
  db-data:
