openapi: 3.0.0
info:
  title: API-Tutorial
  version: '1.0'
  description: API-Tutorial について仕様を説明します。本APIは書籍の扱うサービスに関するAPIであり、これを使用することにより、書籍に対してCRUD処理を行うことができます。
servers:
  - url: 'http://localhost:3000'
tags:
  - name: book
    description: 書籍に関する事項
paths:
  /books:
    get:
      summary: 本の一覧を取得
      tags:
        - book
      description: 本の一覧を返す
      operationId: getBooks
      responses:
        '200':
          description: 本の一覧を取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: リクエストに問題がある
    post:
      tags:
        - book
      summary: 本の追加
      description: 本の追加
      operationId: postBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        '200':
          description: 本が作成された
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: リクエストに問題がある
  '/books/{bookId}':
    put:
      tags:
        - book
      summary: 特定の本の情報を更新
      description: IDによって特定の本を更新する
      operationId: putBooksBookId
      parameters:
        - name: bookId
          in: path
          description: 更新する本のID
          required: true
          schema:
            type: number
      requestBody:
        description: 登録されている本の情報を更新
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: 本が更新された
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: リクエストに問題がある
        '404':
          description: 本が存在しない
    get:
      tags:
        - book
      summary: 特定の本の情報を取得
      description: 特定の本の情報を返す
      operationId: get-books-bookId
      parameters:
        - name: bookId
          in: path
          description: 返すための本のID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 本が取得された
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: リクエストに問題がある
        '404':
          description: 本が存在しません
    delete:
      tags:
        - book
      summary: 特定の本を削除
      description: 特定の本を削除
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          description: 削除する本のID
          required: true
          schema:
            type: number
      responses:
        '400':
          description: リクエストに問題がある
components:
  schemas:
    Book:
      required:
        - id
        - title
        - body
      type: object
      properties:
        id:
          type: number
          example: 4
          readOnly: true
        title:
          type: string
          example: 吾輩は猫である
        body:
          type: string
          example: 名前はまだない。
        createDate:
          type: string
          format: date-time
          example: '2020-01-31T23:59:59+09:00'
          readOnly: true
        updateDate:
          type: string
          format: date-time
          example: '2020-01-31T23:59:59+09:00'
          readOnly: true
  requestBodies:
    Book:
      description: 一覧に追加される本
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Book'
